修复span换行样式无法识别的问题
siyuan-note/siyuan-chrome pull request #11
Opened 2024-11-20 02:57 UTC by ruin1990

修复span换行样式无法识别的问题
https://github.com/siyuan-note/siyuan/issues/13195

如issues 13195沟通，对于span样式换行的文本，在span标签末尾追加br字段，剪报流程完成以后再移除掉，还原网页

2024-11-20 03:10 UTC, 88250 requested changes

2024-11-20 03:10 UTC, 88250 commented on content.js
> +    console.log('siyuanSpansDelBr');
仅在下面 brs 不为空时才打印

2024-11-20 03:10 UTC, 88250 commented on content.js
> +    console.log('siyuanSpansAddBr');
仅在确认要添加 br 才打印，建议打印整个元素以便追踪

2024-11-20 03:29 UTC, ruin1990 commented on content.js
> +    console.log('siyuanSpansAddBr');
哦吼，我才看到，直接删了这部分日志了

2024-11-20 03:44 UTC, 88250 commented on content.js
> +    console.log('siyuanSpansAddBr');
好的

2024-11-20 03:49 UTC, ruin1990 commented on content.js
> +    console.log('siyuanSpansAddBr');
想了下还是加上了日志判断，你看下，我测试只打印object数组速度就快了

2024-11-20 07:07 UTC, ruin1990 commented
我测试发现部分网页的代码块会被此patch影响到，
这里给个测试网址：https://www.cnblogs.com/whuanle/p/18551532
下图左侧是此patch摘录的，右侧是原来的插件摘录的
![image](https://github.com/user-attachments/assets/fceab3f8-fd3d-4501-a25b-db8a63d036f6)

2024-11-20 08:19 UTC, 88250 commented
代码块里面能不能不要加，判断一下。

2024-11-20 10:02 UTC, ruin1990 commented
我担心的不止是代码块，就是可能还会遇到其他正文也出现这个情况
比如这里：https://mp.weixin.qq.com/s/_mpSXqLcBq17VF0p-7KSHg
左侧是原版的，右侧是加了span换行处理的
![image](https://github.com/user-attachments/assets/667b8904-f56a-40f6-99da-233b7c47c6cf)

2024-11-20 10:06 UTC, ruin1990 commented
> 代码块里面能不能不要加，判断一下。

一般怎么判断是否有代码块？我目前感觉都是code段，还有其他特例吗？

2024-11-20 11:36 UTC, ruin1990 commented
把今天讨论的逻辑都加了一遍，测试下面网址是ok的：
https://www.bilibili.com/opus/465490977904921957
https://www.cnblogs.com/whuanle/p/18551532
https://mp.weixin.qq.com/s/stilz-Zm52G_-NUevcWD3w
https://mp.weixin.qq.com/s/_mpSXqLcBq17VF0p-7KSHg

2024-11-20 11:47 UTC, 88250 commented
不好意思，我突然意识到应该把代码放到 Readability.js 里，这样应该就不用再 remove br 了，麻烦试一下。

另外还有点代码风格上的小问题，就是缩进不统一，麻烦改进一下。

2024-11-21 01:10 UTC, ruin1990 commented
Readability.js我还以为是第三方库不能乱动
popup.js的siyuanGetReadability中我主要是看到有个[浏览器剪藏扩展剪藏某些网页代码块丢失注释](https://github.com/siyuan-note/siyuan/issues/5676)的修改参考的
缩进问题我找到原因了编辑器tab和空格混用了
我看看怎么改Readability.js

2024-11-21 01:27 UTC, ruin1990 commented
查阅了下资料：cloneNode(true) 会复制节点的所有属性，包括内联样式，但不会复制外部样式表或CSS样式表规则。也就是说，复制的节点会保留其内联样式（例如 <div style="color: red;">），但不会继承外部样式表中定义的样式。

也就是处理克隆后的节点会没有外部样式，实际代码日志来看也是一致的，测试了最开始issue的链接，日志显示找不到符合条件的元素
No span elements matched the criteria.

得插入到原始文档中，然后设置成不可见？

2024-11-21 02:02 UTC, ruin1990 commented
刚才尝试类似剪贴板那边的操作创建个新节点，但是发现document是不允许插入新的document的。
想了下如果要做比较复杂，需要单独把head和body中需要的部分一个个插入新的不可见节点内。

目前我先做个快速插入和删除的改动，clone以后快速还原，感觉页面都没有去渲染就完成了（至少在我电脑上对用户来说看不出网页的变化）
```diff
diff --git a/popup.js b/popup.js
index 39b2d06..54f3af0 100644
--- a/popup.js
+++ b/popup.js
@@ -201,8 +201,10 @@ const siyuanGetReadability = (tabId) => {
         // 网页换行用span样式word-break的特殊处理 https://github.com/siyuan-note/siyuan/issues/13195
         // 处理会换行的span后添加 <br>，让kernel能识别到换行
         siyuanSpansAddBr(document)
+        const clonedDoc = document.cloneNode(true);
+        siyuanSpansDelBr(document)

-        const article = new Readability(document.cloneNode(true), {
+        const article = new Readability(clonedDoc, {
             keepClasses: true,
             charThreshold: 16,
             debug: true
@@ -212,10 +214,6 @@ const siyuanGetReadability = (tabId) => {
         // console.log(article)
         siyuanSendUpload(tempElement, tabId, undefined, "article", article, window.location.href)
         siyuanClearTip()
-
-        // 网页换行用span样式word-break的特殊处理 https://github.com/siyuan-note/siyuan/issues/13195
-        // 移除由 span_add_br 添加的 <br>，还原原有样式
-        siyuanSpansDelBr(document)
     } catch (e) {
         console.error(e)
         siyuanShowTip(e.message, 7 * 1000)
```

2024-11-21 03:41 UTC, 88250 requested changes

2024-11-21 03:41 UTC, 88250 commented on content.js
> +		let tagName = element.tagName.toLowerCase();
老铁，Tab 和空格的问题。

2024-11-21 03:41 UTC, 88250 commented on content.js
> +            break;
麻烦来个花括号包裹。

2024-11-21 03:41 UTC, 88250 commented on content.js
> +		// 如果父元素是 pre、code、span、math 或与数学相关的类名
Tab/Spaces

2024-11-21 03:41 UTC, 88250 commented on content.js
> +			if (isIgnoredElement(span)) {
Tab/Spaces

2024-11-21 04:41 UTC, ruin1990 commented
我的锅，用记事本Notepad3改的，都换4个空格缩进了

2024-11-21 08:27 UTC, 88250 approved these changes

2024-11-21 08:28 UTC, merged

2024-11-21 08:28 UTC, 88250 commented
感谢，稍后我在扩展商店里面发个新版。